spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: ""
    password: ""
  jpa:
    properties:
      hibernate:
        default_schema: ""
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: update